#!/bin/bash
args=("$@")

export AWS_LAMBDA_RUNTIME_API="127.0.0.1:9009"

LAMBDA_RESOURCE_ATTRIBUTES="cloud.region=$AWS_REGION,cloud.provider=aws,cloud_platform=aws_lambda,faas.name=$AWS_LAMBDA_FUNCTION_NAME,faas.version=$AWS_LAMBDA_FUNCTION_VERSION,faas.instance=$AWS_LAMBDA_LOG_STREAM_NAME";

if [ -z "${OTEL_RESOURCE_ATTRIBUTES}" ]; then
    export OTEL_RESOURCE_ATTRIBUTES=$LAMBDA_RESOURCE_ATTRIBUTES;
else
    export OTEL_RESOURCE_ATTRIBUTES="$LAMBDA_RESOURCE_ATTRIBUTES,$OTEL_RESOURCE_ATTRIBUTES";
fi

if [ -z "${OTEL_SERVICE_NAME}" ]; then
    export OTEL_SERVICE_NAME=$AWS_LAMBDA_FUNCTION_NAME;
fi

if [[ -z "$OTEL_PROPAGATORS" ]]; then
  export OTEL_PROPAGATORS="tracecontext,baggage,xray-lambda"
fi

if [[ -z "$OTEL_TRACES_SAMPLER" ]]; then
  export OTEL_TRACES_SAMPLER="always_on"
fi

# Write env vars to a file for the extension to read
source /opt/shared.sh
write_env_vars


# enable auto instrumentation unless DASH0_DISABLE_AUTO_INSTRUMENTATION is set
if [ -z "$DASH0_DISABLE_AUTO_INSTRUMENTATION" ] || [ "${DASH0_DISABLE_AUTO_INSTRUMENTATION,,}" = "false" ]; then
  export LAMBDA_LAYER_PKGS_DIR="/opt/python";
  export PYTHONPATH="$LAMBDA_LAYER_PKGS_DIR:$PYTHONPATH";
  export PYTHONPATH="$LAMBDA_RUNTIME_DIR:$PYTHONPATH";

  export ORIG_HANDLER=$_HANDLER;
  export _HANDLER="otel_wrapper.lambda_handler";

  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi


exec "${args[@]}"
