#!/bin/bash
#
# Launch the application runtime with the Runtime API pointing to LRAP extension.
# NOTE: This port must be the same as defined in crate::DEFAULT_PROXY_PORT.
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#
args=("$@")
export AWS_LAMBDA_RUNTIME_API="127.0.0.1:9009"

# enable auto instrumentation unless DISABLE_AUTO_INSTRUMENTATION is set
if [ -z "$DISABLE_AUTO_INSTRUMENTATION" ] || [ "${DISABLE_AUTO_INSTRUMENTATION,,}" = "false" ]; then

  export LAMBDA_RESOURCE_ATTRIBUTES="cloud.region=$AWS_REGION,cloud.provider=aws,faas.name=$AWS_LAMBDA_FUNCTION_NAME,faas.version=$AWS_LAMBDA_FUNCTION_VERSION,faas.instance=$AWS_LAMBDA_LOG_STREAM_NAME";

  if [ -z "${OTEL_RESOURCE_ATTRIBUTES}" ]; then
      export OTEL_RESOURCE_ATTRIBUTES=$LAMBDA_RESOURCE_ATTRIBUTES;
  else
      export OTEL_RESOURCE_ATTRIBUTES="$LAMBDA_RESOURCE_ATTRIBUTES,$OTEL_RESOURCE_ATTRIBUTES";
  fi

  if [ -z "${OTEL_SERVICE_NAME}" ]; then
      export OTEL_SERVICE_NAME=$AWS_LAMBDA_FUNCTION_NAME;
  fi

  export LAMBDA_LAYER_PKGS_DIR="/opt/python";
  export PYTHONPATH="$LAMBDA_LAYER_PKGS_DIR:$PYTHONPATH";
  export PYTHONPATH="$LAMBDA_RUNTIME_DIR:$PYTHONPATH";

  export ORIG_HANDLER=$_HANDLER;
  export _HANDLER="otel_wrapper.lambda_handler";

  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

exec "${args[@]}"
