#!/bin/bash
args=("$@")

if [ "$X_LUMIGO_KILLSWITCH" = "true" ]; then
    exec "${args[@]}"
fi
export AWS_LAMBDA_RUNTIME_API="127.0.0.1:9009"
export LUMIGO_ENDPOINT="http://127.0.0.1:9009/v1/traces"
export LUMIGO_TRACER_TOKEN="t_xxxx"

export LAMBDA_RESOURCE_ATTRIBUTES="cloud.region=$AWS_REGION,cloud.provider=aws,faas.name=$AWS_LAMBDA_FUNCTION_NAME,faas.version=$AWS_LAMBDA_FUNCTION_VERSION,faas.instance=$AWS_LAMBDA_LOG_STREAM_NAME";

if [ -z "${OTEL_RESOURCE_ATTRIBUTES}" ]; then
    export OTEL_RESOURCE_ATTRIBUTES=$LAMBDA_RESOURCE_ATTRIBUTES;
else
    export OTEL_RESOURCE_ATTRIBUTES="$LAMBDA_RESOURCE_ATTRIBUTES,$OTEL_RESOURCE_ATTRIBUTES";
fi

if [ -z "${OTEL_SERVICE_NAME}" ]; then
    export OTEL_SERVICE_NAME=$AWS_LAMBDA_FUNCTION_NAME;
fi

# Write env vars to a file for the extension to read
echo "{\"OTEL_SERVICE_NAME\": \"$OTEL_SERVICE_NAME\", \"OTEL_RESOURCE_ATTRIBUTES\": \"$OTEL_RESOURCE_ATTRIBUTES\"}" > /tmp/lumigo_env_vars || true

# enable auto instrumentation unless DISABLE_AUTO_INSTRUMENTATION is set
if [ -z "$DISABLE_AUTO_INSTRUMENTATION" ] || [ "${DISABLE_AUTO_INSTRUMENTATION,,}" = "false" ]; then

  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  PACKAGE_PATH="/opt/init.mjs"
  export NODE_OPTIONS="${NODE_OPTIONS} --import \"${PACKAGE_PATH}\""
fi

exec "${args[@]}"
