#!/bin/bash
args=("$@")

echo "[wrapper] start"

source /opt/shared.sh
setup_otel_env
write_env_vars

# enable auto instrumentation unless DASH0_DISABLE_AUTO_INSTRUMENTATION is set
if [ -z "$DASH0_DISABLE_AUTO_INSTRUMENTATION" ] || [ "${DASH0_DISABLE_AUTO_INSTRUMENTATION,,}" = "false" ]; then

  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  PACKAGE_PATH="/opt/init.mjs"
  export NODE_OPTIONS="${NODE_OPTIONS} --import \"${PACKAGE_PATH}\""
fi

echo "[wrapper] exec"

exec "${args[@]}"
