#!/bin/bash
#
# Launch the application runtime with the Runtime API pointing to LRAP extension.
# NOTE: This port must be the same as defined in crate::DEFAULT_PROXY_PORT.
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#
args=("$@")
export AWS_LAMBDA_RUNTIME_API="127.0.0.1:9009"

export LAMBDA_LAYER_PKGS_DIR="/opt/python";
export PYTHONPATH="$LAMBDA_LAYER_PKGS_DIR:$PYTHONPATH";
export PYTHONPATH="$LAMBDA_RUNTIME_DIR:$PYTHONPATH";

export ORIG_HANDLER=$_HANDLER;
export _HANDLER="otel_wrapper.lambda_handler";

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "executing arg: ${args[@]}"
echo "PYTHONPATH: $PYTHONPATH"

exec "${args[@]}"

#SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
#exec python3 $SCRIPT_DIR/otel_wrapper.py "$@"
