service: dash0-sls-integration-test

provider:
  name: aws
  region: us-west-2

plugins:
  - serverless-dash0

custom:
  dash0:
    endpoint: https://ingress.eu-west-1.aws.dash0-dev.com:4318
    token: ${env:DASH0_DEV_API_TOKEN}
    layerAccountId: 285732642181
    layerVersion: latest
    extensionLogLevel: info

functions:
  hello-python:
    handler: lambdas/python/handler.hello
    runtime: python3.12
    dash0-traced: true

  hello-node:
    handler: lambdas/node/handler.hello
    runtime: nodejs22.x
    dash0-traced: true
